var MAX_1bcc98c3 = '';
MAX_1bcc98c3 += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
MAX_1bcc98c3 += "/* openads=http://www.devmaster.net/adsrvr/www/delivery bannerid=10 zoneid=2 source= */\n";
MAX_1bcc98c3 += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
MAX_1bcc98c3 += "google_ad_client = \"pub-4748087847388234\";\n";
MAX_1bcc98c3 += "google_ad_width = 160;\n";
MAX_1bcc98c3 += "google_ad_height = 600;\n";
MAX_1bcc98c3 += "google_ad_format = \"160x600_as\";\n";
MAX_1bcc98c3 += "google_ad_type = \"text_image\";\n";
MAX_1bcc98c3 += "google_ad_channel = \"\";\n";
MAX_1bcc98c3 += "google_color_border = \"FFFFFF\";\n";
MAX_1bcc98c3 += "google_color_bg = \"FFFFFF\";\n";
MAX_1bcc98c3 += "google_color_link = \"22229C\";\n";
MAX_1bcc98c3 += "google_color_text = \"000000\";\n";
MAX_1bcc98c3 += "google_color_url = \"000000\";\n";
MAX_1bcc98c3 += "//--><"+"/script>\n";
MAX_1bcc98c3 += "<"+"script type=\"text/javascript\"\n";
MAX_1bcc98c3 += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
MAX_1bcc98c3 += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://www.devmaster.net/adsrvr/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_10\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://www.devmaster.net/adsrvr/www/delivery/lg.php?bannerid=10&amp;campaignid=2&amp;zoneid=2&amp;channel_ids=,&amp;loc=http%3A%2F%2Fwww.devmaster.net%2Fengines%2F&amp;cb=a1dc836bbd\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
document.write(MAX_1bcc98c3);
